version: "3.9"
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile_tests

  mysql:
    image: mysql:5.7.44
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty1234
    ports:
      - 3306:3306
