version: "3.9"
services:
  app:
    tty: true
    image: ghcr.io/romangrekov/testrepo:tests
    build:
      context: .
      dockerfile: Dockerfile_tests

  app-coverage:
    tty: true
    image: ghcr.io/romangrekov/testrepo:tests
    build:
      context: .
      dockerfile: Dockerfile_tests
    entrypoint: "python3 -m coverage run -m unittest && python3 -m coverage html"
    volumes:
      - ./coverage:/workdir/htmlcov

  mysql:
    image: mysql:5.7.44
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty1234
    ports:
      - 3306:3306
