name: Build

on: 
  push:
    branches: [main]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        dpkg-deb --build test-service
        echo "Release notes" > body.md
        git tag 1.0

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "test-service.pkg"
        bodyFile: "body.md"